### ISSUE TITLE
Session timeout page

### ISSUE THREAD

**Issue by StephenGill** [alphagov/govuk-design-system-backlog#207] opened 2020-01-16 11:24 UTC
## Why

There isn't currently a pattern showing what a session timeout page should look like or guidance on when session timeouts should kick in.

We do get the occasional question about it - for example: https://github.com/alphagov/govuk-design-system-backlog/issues/104#issuecomment-541008975

## What

Page pattern defining what session timeout pages should look like and guidance on when / how to apply session timeouts.

Source material here: https://github.com/alphagov/govuk-design-system-backlog/issues/104#issuecomment-575079940

**Comment by terrysimpson99** [comment] 2020-01-16 13:56
I'll quote Jennifer's comment on #104:
"We've been discussing the service timeout pattern in our HMRC Working Group. At present, our timeout is set at 15 minutes by default and our discussion have mostly been around the legitimacy of increasing this to, for example, 30 minutes where there's a strong user need. Whether designers are able to do this or not is currently quite hazy, and we have been fielding requests that when this pattern is documented it is made more transparent that times can be increased and guidance is given about the process for doing this. I'm wondering - is this something that should be dealt with on a departmental level, or can this be covered within the GOV.UK Design System?"

Can anyone respond to Jennifer's question?

Secondly, the server-based timeout only measures time since page load. Pressing keys or moving a mouse have no effect on it. A user can spend 12 minutes crafting some text and then nip out for 3 minutes (answer the door, make a drink, call of nature) only to find themselves timed out. Is it feasible to have a timeout that is responsive to user activity?

**Comment by joelanman** [comment] 2020-01-16 13:59
I've often thought it would be a good use of javascript to ping the server to continue the session whenever user activity is detected, to avoid the issue you mentioned.

**Comment by terrysimpson99** [comment] 2020-01-22 17:59
Thanks @joelanman . It'd be great if there were an example solution. Has anybody done this?

**Comment by hannalaakso** [comment] 2020-03-02 13:18
@StephenGill Is this issue a duplicate of https://github.com/alphagov/govuk-design-system-backlog/issues/103 (and perhaps https://github.com/alphagov/govuk-design-system-backlog/issues/104)?

**Comment by hannalaakso** [comment] 2020-06-18 08:23
Closing this as it's a duplicate of https://github.com/alphagov/govuk-design-system-backlog/issues/103.

**Closed by hannalaakso** 2020-06-18 08:23 UTC
Labels: feature-request
