### ISSUE TITLE
Radio buttons - Uncentred dot on the radio button when page is zoomed out

### ISSUE THREAD

**Issue by domjstone** [alphagov/govuk-design-system-backlog#296] opened 2024-06-06 09:35 UTC
Radio button component - Uncentred radio button when page is zoomed out 

![image](https://github.com/alphagov/govuk-design-system-backlog/assets/148347340/293cf8ad-c3ed-4006-96f6-b6757f62a737)

The radio button black centres seem to show high left off centre 
NB. This seems more obvious with the Edge browser or at lower levels of zoom in Chrome (second screenshot is 75%)

**Comment by querkmachine** [comment] 2024-06-06 10:58
I believe this is a duplicate of a question raised here: https://github.com/alphagov/govuk-design-system-backlog/issues/59#issuecomment-1545502525. A response for it was given in this subsequent comment: https://github.com/alphagov/govuk-design-system-backlog/issues/59#issuecomment-1545549904.

The short answer is that this is a factor of how browsers round non-whole pixel values, which can cause things to look weird at particular zoom levels. We don't really have much control over how this manifests.

**Closed as not planned by querkmachine** 2024-06-06 10:58 UTC
