### ISSUE TITLE
Styling Government staff services

### ISSUE THREAD

**Issue by owenm6** [alphagov/govuk-design-system-backlog#160] opened 2018-09-27 10:07 UTC
## What
A consistent way to style Government staff services. 

## Why
Without the most recognisable visual elements of GOV.UK, the Crown and GDS transport font, Government staff services use a varying amount of the GOV.UK design language. Teams should have clear guidance so they can focus on designing the service. Guidance will also ensure services look consistent, which is especially important for staff who move between services to do their job.

The guidance is published in the Home Office Design System and is being used (to varying degrees) on services at the Home Office, MOJ and DWP.

## Links and examples
Style guide - https://home-office-digital-patterns.herokuapp.com/styles
A version of the prototype kit with the styles - https://github.com/UKHomeOffice/ho-style-prototype-kit

**Comment by timpaul** [comment] 2019-02-04 11:33
Michael, if you don't mind we're going to close this issue as a duplicate of [this one](https://github.com/alphagov/govuk-design-system-backlog/issues/185) in the 'To do' column.

**Closed by timpaul** 2019-02-04 11:33 UTC
